# Generated by Django 4.1.7 on 2023-04-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DojoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojo_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('kyu', models.IntegerField(default=8)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chexo_app.dojolist')),
            ],
        ),
    ]
